# Generated by Django 4.0 on 2024-08-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
